### ISSUE TITLE
Unicode escape sequence doesn't work

### ISSUE THREAD

**Issue by schani** [elm-lang/elm-compiler#1623]
```
---- elm-repl 0.18.0 -----------------------------------------------------------
 :help for help, :exit to exit, more at <https://github.com/elm-lang/elm-repl>
--------------------------------------------------------------------------------
> '\ude1c'
-- SYNTAX PROBLEM -------------------------------------------- repl-temp-000.elm

Elm uses double quotes for strings. Switch the ' to " on both ends of the string
and you should be all set!

3|   '\ude1c'
            ^
Maybe <http://elm-lang.org/docs/syntax> can help you figure it out.


> '\xde1c'
elm-make: elm-stuff/build-artifacts/0.18.0/user/project/1.0.0/Repl.elmo: commitAndReleaseBuffer: invalid argument (invalid character)
elm-make: thread blocked indefinitely in an MVar operation

> '\xd83d'
/private/var/folders/2x/3mx87c6575l5wyx1w2skt3g40000nw/T/416f123722488456/repl-temp-000.js:3177
var _user$project$Repl$d_e_l_t_r_o_n_3_0_3_0 = d_e_l_t_r_o_n_3_0_3_0 = _elm_lang$core$Native_Utils.chr('𑠧);
                                                                                                       ^^^^^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by robx** [comment]
To summarize, we have:

* high surrogates `\xd800..\xdbff`: invalid Javascript
* low surrogates `\xdc00..\xdfff`: crash
* `\x2028` (line separator), `\x2029` (paragraph separator): invalid Javascript

**Comment by evancz** [comment]
In my development build, I am getting the following error:

```
-- PARSE ERROR -------------------------------------------------------- temp.elm

I ran into an invalid Unicode escape character:

5|   '\ude1c'
      ^^
Here are some examples of valid Unicode escape characters:

    \u{0041}
    \u{03BB}
    \u{6728}
    \u{1F60A}

Notice that the code point is always surrounded by curly braces. They are
required!
```

The next release does not follow the escaping conventions developed before UTF-8 was so common. Instead it has folks say `\u{0041}` where you list the full code point in hex between the curly braces. It is turned into valid JS internally. This is part of the parser changes that make the next release major.

Anyway, thank you for the report!
